### ISSUE TITLE
McAfee detects virus in Hackaday.io File for windows setup

### ISSUE THREAD

**Issue by digamesystems** [hyOzd/serialplot#29]
It looks like McAfee is detecting a virus in the publicly available binary for your utility. -- 'Might be worth checking.

**Comment by hyOzd** [comment]
@digamesystems Thanks for notifying me. But I have a few questions.

Which specific file are you having this warning with? File name, size etc? Where did you download it from?

Can you calculate the `sha1sum` of the file?

As a precaution I've checked the sha1sum of some of the files that I downloaded from `serialplot.ozderya.net/downloads` page and compared them with my local copies. They checkout. So this could be a false alarm from your antivirus, which isn't surprising to me.

There was only one file that I couldn't check because I didn't have it in my local archive. But I remember that one was a mistake that I forgot to remove. So I removed it. File was named: `serialplot-0.12.0-win32.exe.exe`

**Comment by digamesystems** [comment]
@hyOzd Thanks for the reply.

**Comment by hyOzd** [comment]
This looks like a warning even before the file is downloaded. I think it is just being cautious. I've tried kaspersky's online file scanner to see if there is something like a system call (I don't expect a virus/trojan) that triggers the scanner. It didn't report anything.

Nevertheless I understand your concern. It is a dangerous game to download some exe file from internet and run it. My recommendation for you is to build the SerialPlot from source. It can be a bit challenging if you've never worked with Qt before, but it is easy once you figure a few things out.

Another option is to use a 'sandboxing' tool to run EXEs on your computer. But serialplot obviously needs access to your serialport. You will need an sandbox application that gives you control over serialports/usb access.
