### ISSUE TITLE
Is it possible that for each channel, you can specify "Number Type"?

### ISSUE THREAD

**Issue by VictorTagayun** [hyOzd/serialplot#30]
Is it possible that for each channel, you can specify "Number Type"?
Like:
CH1 = 8bit
CH2 = 16bit 
CH3 = 24bit

**Comment by hyOzd** [comment]
No this is not possible.

**Comment by VictorTagayun** [comment]
Will you consider for a future feature?

**Comment by hyOzd** [comment]
No, I think it becomes too specific at this point. I would implement a scriptable data format instead. So that anyone can implement the format they need. But I don't plan to work on that anytime soon .

At the moment my recommendation for when you need a really custom data format is to create script that would read the data from serialport, parse it and pass it to the serialplot via virtual serialport.

**Comment by VictorTagayun** [comment]
Thanks! I don't know how to do scripting, but I'll just log it and manipulate it in some spreadsheet instead for analysis.
